FROM node:13.12.0-alpine as builder
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

COPY package.json /app
COPY public public/
COPY src /app/src
COPY parms /app/.env

RUN npm install --silent
RUN npm run build

COPY server.js /app/server.js

EXPOSE 10000
